### PR TITLE
Oralhistory fixes

### PR DESCRIPTION
**Pull request by ryaholm**
Added features to OHP:

- clicking on a tag jumps to that time feature
- fixed incorrect app id during project creation (using ```name="Oral Histories"```) instead of ```id=76```

I am also testing to see if this passes tests on django 1.11.14

### CODE REVIEW

**Comment by ryaholm** [comment]
@SillyInventor Removed twitter_bootstrap, which is like a four-years-since-last-update project.

That fixes the test errors.

**Comment by SillyInventor** [comment]
I am afk until tonight, could you navigate to each page and check the layout? I would like to know why twitter bootstrap neded removal and why it broke things. Should be fine.

**Comment by SillyInventor** [comment]
Leaving this here as a reminder to remove those less changes.

**Comment by ryaholm** [comment]
switched to #458

**Pull request closed without merging**
