### PR TITLE
Alpha test of gitmodule incorporation of static pages -- updates urls…

### PR DESCRIPTION
**Pull request by ryaholm**
….py to have a catchall for static pages that goes to /website/www, adds the git submodule for website, and adds the actual website repo from git.hass...

### CODE REVIEW

**Comment by ryaholm** [comment]
Some things I'm wondering about is how the SSH into git@git.hass.rpi.edu is going to be automated. Will the server have a saved SSH password for git.hass?

**Comment by SillyInventor** [comment]
We'll need to add an ssh for git.hass to travis' settings and local_settings to do it this way. @joshuacherry what do you think?

**Comment by joshuacherry** [comment]
git.hass.rpi.edu does not have a campus firewall exception at this point so travis CI will not be able to access that destination.  Currently, I will not be opening port 22 on git.hass.rpi.edu. I'm not completely against the idea of allowing ssh for the git user from [travi-ci's IP ranges](https://docs.travis-ci.com/user/ip-addresses/), but there are a number of additional security measures I would want to implement on that server beforehand.
  
**IF** I create a firewall exception (after implementing additional security measures) the best method for access would probably be a balance between [Encrypted files](https://docs.travis-ci.com/user/encrypting-files/) and [Encrypted Variables in .travis.yml](https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml) to store a read-only deployment key.  

I think it's also important to point out that your repository at git.hass.rpi.edu is private. If your goal is to allow members of the public to use [https://github.com/RPI-HASS/rpi_csdt_community.git](https://github.com/RPI-HASS/rpi_csdt_community.git), you might want to avoid automatically downloading a private repo via .gitmodules since that would negatively affect others' ability to clone and use this repo easily.
  
You may want to consider some form of `tests` directory with example data that can be used in the interim.  Instead of using `.gitmodules` to download a submodule, you could have `.travis.yml` and your Vagrantfile copy the test data into the desired `website/www` directory location and performa and desired tests then.

**Comment by SillyInventor** [comment]
Perhaps you're right. Let's remove the submodule, keep the url changes. Then, Josh, if you could have ansible compile into static/website we'll have a working version. *crosses fingers*

**Comment by ryaholm** [comment]
Thanks Josh      💯

**Comment by joshuacherry** [comment]
@SillyInventor Currently I'm using the below snippet in the virtualhost.
```
      location ^~ /wwwstatic {
          alias /var/www/csdt_static/www;
      }
```
It's my understanding that the static folder is overwritten each time the repository is cloned. The reason I moved the website repo outside the Django app directory and used a location that does not proxy requests to the django process is so that harp compiled files do not get overwritten each time you push a commit to this repo.

Both this repository and the private repo use automated hooks to clone their data. If you want to store the website repo inside this repository on the server, would you mind committing an update to the `.gitignore` file for the exact location of the website repository?

**Comment by ryaholm** [comment]
:saxophone:

**Comment by SillyInventor** [comment]
@joshuacherry @ryaholm added the .gitignore. I think it depends on how you go about the update in ansible. If you're calling git pull, that's no problem, which if local_settings isn't being overwritten, I suspect you should be A-OK. But if you're removing the base directory, then calling git clone / setup again, then it will definitely delete everything. In which case you would need to add to the ansible script something like:
 ```bash
cd /static/website 
git clone git.hass..... 
cd website
harp compile
```

**Comment by joshuacherry** [comment]
I've updated the path and removed the nginx location. Feel free to implement this on the develop branch so the dev server can update. If you run into issues please let me know,

**Comment by SillyInventor** [comment]
@joshuacherry still having trouble getting this to work on dev. Did you change the ansible script?

**Comment by joshuacherry** [comment]
@SillyInventor It seems to be working from my perspective. https://dev.csdt.rpi.edu/static/website/www/

Was there some other functionality you needed?

**Comment by SillyInventor** [comment]
There is something messed up, but it's not on your end. Thanks @joshuacherry.

**Comment by SillyInventor** [comment]
@joshuacherry, is it at all possible the githook for dev isn't firing?

**Comment by joshuacherry** [comment]
@SillyInventor 
```
2017-06-01 12:55:19,808 [INFO ]  HEAD is now at e5dfa9d Urls static (#36)
```
Seems like the hook fired correctly and successfully cloned the repo. The post-deploy tasks also ran. There is some information that might be more useful to you than me though.
```
/opt/rpi_csdt_community/bin/pip install --upgrade -r /var/www/csdt.rpi.edu/requirements.txt; cd /var/www/csdt.rpi.edu/ && git submodule foreach git pull origin master; /opt/rpi_csdt_community/bin/python /var/www/csdt.rpi.edu/manage.py collectstatic --noinput; chown -R root:www-data /var/www/csdt.rpi.edu

...
2017-06-01 12:55:47,943 [INFO ]  Found another file with the destination path 'admin/img/search.svg'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
...
2017-06-01 12:55:47,945 [INFO ]  1670 static files copied to '/var/www/csdt.rpi.edu/collected_static', 4977 unmodified.
...
2017-06-01 12:55:47,945 [ERROR]  From https://github.com/CSnap/CSnap-Modules
2017-06-01 12:55:47,945 [ERROR]   * branch            master     -> FETCH_HEAD
2017-06-01 12:55:47,945 [ERROR]     77a8589..db98a6f  master     -> origin/master
2017-06-01 12:55:47,945 [ERROR]  From https://github.com/GK-12/Snap--Build-Your-Own-Blocks
2017-06-01 12:55:47,946 [ERROR]   * branch            master     -> FETCH_HEAD
2017-06-01 12:55:47,947 [INFO ]  Deploy completed!
```
And the output of `git status`
```
$ git status
On branch develop
Your branch is up-to-date with 'origin/develop'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)
  (commit or discard the untracked or modified content in submodules)

        modified:   static/applications/CSnap-Modules (new commits)
        modified:   static/csnap (new commits, modified content)
```

I can manually run `git checkout .` if you think removing the modified unstaged files will help your app.

**Comment by ryaholm** [comment]
@joshuacherry 

Hi Josh,
We're trying to determine why the dev.csdt.rpi.edu isn't catching the final catch-all (?P<path>.*) regex in urls.py. When we look at the 404 on dev, it looks like this:
screen shot 2017-06-01 at 3 22 18 pm

Our regex catchall should be #38 on that list, which /should/ make the 404 be a 404 after searching the static directory (not urls.py's regexes). This is what a 404 looks like on our builds of the develop branch on our local computers:
screen shot 2017-06-01 at 3 22 32 pm

So it appears that the dev.csdt.rpi.edu site isn't including that final regex to move the path search into the static folder using settings.STATIC_WEBSITE_ROOT. We expect that we should get a different 404 if it were (similar to the second screen shot). Do you have any idea why we aren't getting it to work? I would think there is a possibility we have the wrong folder location in settings.py for STATIC_WEBSITE_ROOT, but then again we suspect we would have a different 404. Especially since it appears to work on our local computers (where we put the website/www compiled harp files into /static/).

Thanks for your time.

**Pull request merged**
