### PR TITLE
Add testing

### PR DESCRIPTION
**Pull request by serenasyw**

### CODE REVIEW

**Comment by SillyInventor** [comment]
@serenasyw you definitely didn't make this PR last night :( .... this is not like a class where you can do the work an hour before. I expect you to put in the 12 hours we discussed through the week.

We have standards about linting. To test against those standards run:
```console
pip install flake8
flake8 .
```
That's why you have errors in the testing from Travis. Ignore the bare except errors when you run locally.

You have conflicts with the develop branch. At this point you can either go in and resolve the conflicts, or start over from the most recent changes. As a general rule make sure 1. that you're working on the most recent version of the repo, push quickly and frequently.

**Comment by serenasyw** [comment]
Sorry I just realized that I just pushed the updates but did not make the
pull request... I am going to resolve the conflicts now.

2018-02-21 10:20 GMT-05:00 Silly Inventor <notifications@github.com>:

**Comment by SillyInventor** [comment]
Lol, I just noticed you're making the PR to master. For this branch we use a branch->develop->master git flow.

**Comment by SillyInventor** [comment]
To be clear, that's my fault, I should have mentioned it.

**Pull request closed without merging**
