### PR TITLE
Gis fixes

### PR DESCRIPTION
**Pull request by SillyInventor**
Opening PR for discussion purposes

### CODE REVIEW

**Comment by SillyInventor** [comment]
You're making progress...

It still requires a local_settings.py file to run. That's not the end of the world, but you should really put in dummy keys for the gis_csdt settings file, so that it will build on vagrant up, then take local_settings to overwrite those if you're using or testing gis.

You can't have both the CSnap and your local SGIS-Backend installed in the same directory.

You should setup the database as django.contrib.gis.db.backends.postgis, rather than just eliminating the assert.
@RuofanLiu @chuck211991

**Comment by RuofanLiu** [comment]
the latest version with dummy keys are pushed to the gis_fixes branch.

**Comment by SillyInventor** [comment]
Did you forget to push?

**Comment by RuofanLiu** [comment]
Sorry for the confusion. You can find it here at https://github.com/RPI-HASS/rpi_csdt_community/tree/gis_fixes

**Comment by RuofanLiu** [comment]
now it only displays the root page, I'm working on it.

**Comment by SillyInventor** [comment]
@RuofanLiu Some things to note:

1. You don't want to add a local_settings file. While it might be tempting, consider what local_settings is for. Those are meant to house things that are specific to the local computer. Like if I wanted to specify a password or IP address for the server, I would make a local_settings file. So any general setting should happen in settings, while letting the user create local_settings as they need them.
2. If you want to be able to build without having the keys, then the best approach is to check whether you have a local_settings file, and if you don't, define some dummy keys. You should put that where it's throwing the exception, in the settings file. A try except statement is good for that.
3. You accidentally added a bunch of .DS_Store files. Git helpfully lists the files you're adding when you commit, so make sure to double check that those are the files you want to change in the future.

Keep at it.

CC @chuck211991

**Comment by RuofanLiu** [comment]
A problem now is that after setting up everything in the rpi_csdt_community/rpi_csdt_community (current directory )directory, it told me that it can't find local_settings in gis_csdt/settings.py(backend directory), which is weird. Trying to fix it

**Comment by RuofanLiu** [comment]
It worked.

**Comment by RuofanLiu** [comment]
Please see the latest version.

**Pull request closed without merging**
